Repository webpack-contrib/webpack-command, pull requests merged in 2018-06, with the labels that each got.

#38 fix: context overriden by flags default value. fixes #36
  lib/config.js
  lib/flags/general.js
  test/tests/__snapshots__/config.js.snap
  test/tests/__snapshots__/flags.js.snap
  test/tests/__snapshots__/reporters.js.snap
  test/tests/config.js
  test/tests/flags/__snapshots__/debug.js.snap
  test/tests/flags/__snapshots__/devtool.js.snap
  test/tests/flags/__snapshots__/entry.js.snap
  test/tests/flags/__snapshots__/reporter.js.snap
  test/tests/flags/__snapshots__/run-mode.js.snap
  test/tests/flags/__snapshots__/watch.js.snap
Labels: kind 🐛 bug, p¹ 🔥🔥🔥 critical

#40 feat: export `wp` binary in package to avoid binary name conflicts
  package.json
Labels: c² ⋅ feedback wanted, kind✨ feature, p² 🔥🔥 important, v⁴ ⋅ minor

#39 feat: add JSON reporter. fixes #16
  lib/compiler.js
  lib/reporters/JsonReporter.js
  package.json
  test/fixtures/reporters/json/json-multi.js
  test/fixtures/reporters/json/json.js
  test/fixtures/reporters/json/problems/entry-problems.js
  test/fixtures/reporters/json/problems/image.jpg
  test/fixtures/reporters/json/problems/problems.js
  test/tests/__snapshots__/reporters.js.snap
  test/tests/reporters.js
Labels: kind✨ feature, p² 🔥🔥 important, v⁴ ⋅ minor

#35 fix: add handling for exit codes on error
  lib/cli.js
  lib/compiler.js
  test/fixtures/common/test-reporter.js
Labels: kind ✨ enhancement, p² 🔥🔥 important

#24 feat: allow --reporter to be relative to CWD
  lib/compiler.js
  test/tests/__snapshots__/cli.js.snap
  test/tests/cli.js
Labels: kind ✨ enhancement, p³ 🔥 nice to have
