Repository webpack-contrib/webpack-command, pull requests merged in 2018-05, with the labels that each got.

#10 chore: move from peer. fixes #8
  package-lock.json
  package.json
Labels: kind 🐛 bug, p¹ 🔥🔥🔥 critical

#9 Add badge for install size
  README.md
Labels: kind ✨ enhancement, waiting on upstream

#20 fix: check for --run-dev and --run-prod before other flags
  lib/flags/general.js
  test/tests/flags/__snapshots__/run-mode.js.snap
Labels: kind 🐛 bug, p² 🔥🔥 important
